# Generated by Django 4.2.5 on 2023-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_acessomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessomedico',
            name='token',
            field=models.CharField(default='UbYCdT6v', max_length=20),
        ),
    ]
